interface/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :sentences, only: [:show]
  resources :bert_tags, only: [:edit, :update]
  resources :articles
  resources :locations  
  resources :states  
  resources :counties  
  resources :topics  
  resources :neighborhoods  
  resources :zip_codes  
  resources :article_locations  
  resources :collections
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
  
  root to: 'articles#index'
  
  post '/collections(/:id)/import', controller: :collections, action: :import, as: 'import_collections'
  get '/collections(/:id)/points', controller: :collections, action: :points
  get '/collections(/:id)/polys', controller: :collections, action: :polys
  get '/collections(/:id)/map', controller: :collections, action: :map
  get '/collections(/:id)/locations', controller: :collections, action: :locations
  get '/collections(/:id)/locations(/:location_id)', controller: :collections, action: :location
  get '/collections(/:id)/zip_codes', controller: :collections, action: :zip_codes
  get '/collections(/:id)/authors', controller: :collections, action: :authors
  get '/collections(/:id)/topics', controller: :collections, action: :topics
  get '/collections(/:id)/census_tracts', controller: :collections, action: :census_tracts
  get '/collections(/:id)/counties', controller: :collections, action: :counties
  get '/collections(/:id)/neighborhoods', controller: :collections, action: :neighborhoods
  get '/collections(/:id)/featured', controller: :collections, action: :featured
  get '/collections(/:id)/articles', controller: :collections, action: :articles
  get '/collections(/:id)/tasks', controller: :collections, action: :tasks
  get '/collections(/:id)/info', controller: :collections, action: :info
  get '/collections(/:id)/simple_articles', controller: :collections, action: :simple_articles
  get '/collections(/:id)/article_locations', controller: :collections, action: :article_locations
  get '/collections(/:id)/featured_articles', controller: :collections, action: :featured_articles
  get '/collections(/:id)/featured_article_locations', controller: :collections, action: :featured_article_locations
  
end

interface/app/models/article_location.rb
class ArticleLocation < ApplicationRecord
  belongs_to :article, :counter_cache => true
  belongs_to :location
  belongs_to :flag, optional: true
  
  after_commit :flush_cache

  def flush_cache
    Rails.cache.delete([self, :snippet])
  end
  
  def self.before(before)
    where('articles.published_at <= ?', before.to_time.end_of_day)
  end

  def self.after(after)
    where('articles.published_at >= ?', after.to_time.beginning_of_day)
  end
    
  def snippet
    Rails.cache.fetch([self, :snippet], expires_in: 12.hours) { snippet! }
  end
  
  def snippet!
    name = location.name
    name = name.gsub(/['’]/i, "'")
    regex = Regexp.new(Regexp.escape(name))
    text = nil
    data = nil
    article.sentences.each do | sentence |
      content = sentence.content
      content = content.gsub(/['’]/i, "'")
      data = content.match(regex)
      if not data.blank?
        text = content
        break
      end
    end
    
    if text.blank?
      return ""
    end

    if data.blank?
      return ""
    end

    offset = data.offset(0)

    startpadding = 20
    endpadding = 75

    length = text.length

    starting = [0, offset[0] - startpadding].max
    ending = [length, offset[1] + endpadding].min

    return "...#{text}..."
  end
end

interface/app/controllers/article_locations_controller.rb
class ArticleLocationsController < ApplicationController
  before_action :set_article_location, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :edit, :update]
  
  # GET /article_locations
  # GET /article_locations.json
  def index
    @article_locations = ArticleLocation.all.paginate(page: params[:page], per_page: params[:per_page])
    
    if params[:comment].present?
      comment = params[:comment]
      if comment
        @article_locations = @article_locations.where("article_locations.comment ILIKE ?", "%#{comment}%")
      end
    end
    
    if params[:flagged].present?
      flagged = ActiveRecord::Type::Boolean.new.deserialize(params[:flagged])
      if flagged
        @article_locations = @article_locations.joins(:location).where("article_locations.flagged = true OR locations.flagged = true")
      else
        @article_locations = @article_locations.joins(:location).where("article_locations.flagged = false AND locations.flagged = false")
      end
    end
    
    if params[:flag].present?
      flag = ActiveRecord::Type::Boolean.new.deserialize(params[:flag])
      if flag
        @article_locations = @article_locations.where("article_locations.flag_id IS NOT NULL OR locations.flag_id IS NOT NULL")
      else
        @article_locations = @article_locations.where("article_locations.flag_id IS NULL AND locations.flag_id IS NULL")
      end
    end
    
    respond_to do |format|
      format.html
      format.json
      format.csv { send_data @article_locations.to_csv }
    end
  end

  # GET /article_locations/1
  # GET /article_locations/1.json
  def show
  end

  # GET /article_locations/new
  def new
    @article_location = ArticleLocation.new
  end

  # GET /article_locations/1/edit
  def edit
  end

  # POST /article_locations
  # POST /article_locations.json
  def create
    @article_location = ArticleLocation.new(article_locations_params)

    respond_to do |format|
      if @article_location.save
        format.html { redirect_to @article_location, notice: 'Article Location was successfully created.' }
        format.json { render :show, status: :created, location: @article_location }
      else
        format.html { render :new }
        format.json { render json: @article_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /article_locations/1
  # PATCH/PUT /article_locations/1.json
  def update
    respond_to do |format|
      if @article_location.update(article_location_params)
        format.html { redirect_to @article_location, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article_location }
      else
        format.html { render :edit }
        format.json { render json: @article_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /article_locations/1
  # DELETE /article_locations/1.json
  def destroy
    @article_location.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path, notice: 'Article Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article_location
      @article_location = ArticleLocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_location_params
      params.require(:article_location).permit(:location_id, :article_id, :flagged, :comment, :flag_id)
    end
end

interface/app/views/article_locations/_form.html.erb
<%= form_with(model: article_location, local: true) do |form| %>
  <% if article_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article_location.errors.count, "error") %> prohibited this article_location from being saved:</h2>

      <ul>
      <% article_location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Article (#{article_location.article_id})" %>
    <%= article_location.article.title %>
  </div>
  
  <div class="field">
    <%= form.label "Location (#{article_location.location_id})" %>
    <%= link_to article_location.location.name, article_location.location %>
  </div>

  <div class="field">
        <%= form.label :comment %>
        <%= form.text_area :comment %>
  </div>
  
  <div class="field">
      <%= form.label :flagged %>
      <%= form.check_box :flagged %>
  </div>
  
  <div class="field">
  <%= form.collection_select :flag_id, Flag.order(:reason), :id, :detail, include_blank: "Select Reason" %>
  </div>
      
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

interface/app/views/article_locations/edit.html.erb
<h1>Editing Article</h1>

  <div class="field">
    <p>Snippet:</p>
    <%= @article_location.snippet %>
  </div>

<%= render 'form', article_location: @article_location %>

<%= link_to 'Show', @article_location %> |
<%= link_to 'Back', article_locations_path %>

interface/app/views/article_locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Article Locations</h1>

<table>
  <thead>
    <tr>
      <th>Identifier</th>
      <th>Article Id</th>
      <th>Location</th>
      <th>County</th>
      <th>Snippet</th>
      <th>Comment</th>
      <th width=100>Flag</th>
    </tr>
  </thead>
  <tbody>
    <% @article_locations.each do |article_location| %>
      <tr>
        <td><%= link_to article_location.id, edit_article_location_path(article_location) %></td>
        <td><%= link_to article_location.article.id, article_location.article %></td>
        <td><%= link_to article_location.location.name, article_location.location %></td>
        <td><%= link_to article_location.location.county.try(:name) || "", article_location.location.county %></td>
        <td><%= article_location.snippet %></td>
        <td><%= article_location.comment %></td>
        <td><%= article_location.flag.try(:reason) || article_location.location.flag.try(:reason) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @article_locations %>

interface/app/views/article_locations/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

interface/app/views/article_locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= @article_location.article.title %></strong>
</p>

<p>
  <strong><%= link_to @article_location.location.try(:name), @article_location.location %></strong>  
</p>

<p>
  <strong><%= @article_location.comment %></strong>
</p>

<p>
  <strong><%= @article_location.flagged %></strong>
</p>

<%= link_to 'Edit', edit_article_location_path(@article_location) %> |
<%= link_to 'Back', article_locations_path %>