interface/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :sentences, only: [:show]
  resources :bert_tags, only: [:edit, :update]
  resources :articles
  resources :locations  
  resources :states  
  resources :counties  
  resources :topics  
  resources :neighborhoods  
  resources :zip_codes  
  resources :article_locations  
  resources :collections
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
  
  root to: 'articles#index'
  
  post '/collections(/:id)/import', controller: :collections, action: :import, as: 'import_collections'
  get '/collections(/:id)/points', controller: :collections, action: :points
  get '/collections(/:id)/polys', controller: :collections, action: :polys
  get '/collections(/:id)/map', controller: :collections, action: :map
  get '/collections(/:id)/locations', controller: :collections, action: :locations
  get '/collections(/:id)/locations(/:location_id)', controller: :collections, action: :location
  get '/collections(/:id)/zip_codes', controller: :collections, action: :zip_codes
  get '/collections(/:id)/authors', controller: :collections, action: :authors
  get '/collections(/:id)/topics', controller: :collections, action: :topics
  get '/collections(/:id)/census_tracts', controller: :collections, action: :census_tracts
  get '/collections(/:id)/counties', controller: :collections, action: :counties
  get '/collections(/:id)/neighborhoods', controller: :collections, action: :neighborhoods
  get '/collections(/:id)/featured', controller: :collections, action: :featured
  get '/collections(/:id)/articles', controller: :collections, action: :articles
  get '/collections(/:id)/tasks', controller: :collections, action: :tasks
  get '/collections(/:id)/info', controller: :collections, action: :info
  get '/collections(/:id)/simple_articles', controller: :collections, action: :simple_articles
  get '/collections(/:id)/article_locations', controller: :collections, action: :article_locations
  get '/collections(/:id)/featured_articles', controller: :collections, action: :featured_articles
  get '/collections(/:id)/featured_article_locations', controller: :collections, action: :featured_article_locations
  
end

interface/app/models/location.rb
class Location < ApplicationRecord
  
  after_save :did_save
  before_save :will_save
  
  belongs_to :flag, optional: true
    
  has_many :bert_tags, :dependent => :nullify
  has_many :sentences, :through => :bert_tags
  has_many :articles, :through => :sentences
  
  validates :name, uniqueness: { scope: [:viewbox, :bias] }

  belongs_to :zip_code, primary_key: 'ogc_fid', optional: true
  belongs_to :census_tract, primary_key: 'ogc_fid', optional: true
  belongs_to :county, primary_key: 'ogc_fid', optional: true
  belongs_to :neighborhood, primary_key: 'ogc_fid', optional: true
  
  def will_save
    if self.will_save_change_to_osm_results? || self.will_save_change_to_google_results? || self.will_save_change_to_use_osm?
      self.set_results
      self.set_latlng
      self.set_wkb_geometry
      self.set_formatted_address
      self.set_geometry_type
    end
    if self.will_save_change_to_county_id?
      self.county_geoid = self.county.try(:geoid)
    end
    if self.will_save_change_to_neighborhood_id?
      self.neigborhood_geoid = self.neighborhood.try(:geoid_nh)
    end
    if self.will_save_change_to_census_tract_id?
      self.census_geoid = self.census_tract.try(:geoid)
    end
    if self.will_save_change_to_zip_code_id?
      self.zipcode_geoid = self.zip_code.try(:geoid10)
    end
  end
  
  def did_save
    if self.saved_change_to_name?
      self.fetch_osm
      self.fetch_google
    end
    if self.saved_change_to_wkb_geometry?
      puts "saved_change_to_wkb_geometry"
      self.set_zip_code
      self.set_census_tract
      self.set_county
      self.set_neighborhood
    end
  end
  
  def is_gpe_or_unknown?
    if self.google_results.present?
      results = self.google_results['results']
      if results.present? && results.length > 0
        types = results[0]['types']
        if types.present? && types.length > 0
          return types.any?{|x| ["administrative_area_level_1", "administrative_area_level_2", "administrative_area_level_3", "locality", "sublocality", "neighborhood"].include?(x)}
        end
      else
        return true # is unknown
      end
    end
    
    return false
  end
    
  def fetch_results
    parsed_osm_result = self.parsed_osm_result
    parsed_google_result = self.parsed_google_result
    if self.is_gpe_or_unknown? && parsed_osm_result.present? && self.use_osm
      return parsed_osm_result
    end
    if parsed_google_result.present?
      return parsed_google_result
    end
    return parsed_osm_result
  end
  
  def set_results
    self.results = self.fetch_results
  end
  
  def parsed_google_result
    if not self.google_results.present?
      return nil
    end
    
    data = {}
    source = "unknown"
    formatted_address = nil
    lat = nil
    lng = nil
    geojson = nil
    queried_for = nil
    boundingbox = []
    type = []
    source = "google"
    results = self.google_results['results']
    if results.present? && results.length > 0
      display_name = results[0]['formatted_address']
      if display_name.present?
        formatted_address = display_name
      end
      type = results[0]['types']
      geometry = results[0]['geometry']
      if geometry.present?
        location = geometry['location']
        if location.present?
          lat = location['lat']
          lng = location['lng']
          geojson = {}
          geojson['type'] = "Point"
          geojson['coordinates'] = [ lng, lat ]
        end
        viewport = geometry['viewport']
        if viewport.present?            
          nlat = viewport['northeast']['lat']
          nlon = viewport['northeast']['lng']
          slat = viewport['southwest']['lat']
          slon = viewport['southwest']['lng']
          boundingbox =[slat, nlat, slon, nlon]
        end
      end        
    end
    
    data["source"] = source
    data["lat"] = lat
    data["lng"] = lng
    data["formatted_address"] = formatted_address
    data["type"] = type
    if queried_for.present?
      data["queried_for"] = queried_for
    end
    data["boundingbox"] = boundingbox
    if geojson.present?
      data["geojson"] = geojson
    end
    return data
  end
  
  def parsed_osm_result
    if not self.osm_results.present?
      return nil
    end
    
    if self.osm_results.length == 0
      return nil
    end
    
    data = {}
    source = "unknown"
    formatted_address = nil
    lat = nil
    lng = nil
    geojson = nil
    queried_for = nil
    boundingbox = []
    type = []
    osm_result = self.osm_results[0]
    source = "osm"
    if osm_result['type'].present?
      type = [osm_result['type']]
    end
    if osm_result['display_name'].present?
      formatted_address = osm_result['display_name']
    end
    if osm_result['lat'].present?
      lat = osm_result['lat']
    end
    if osm_result['lon'].present?
      lng = osm_result['lon']
    end
    if osm_result['geojson'].present?
      geojson = osm_result['geojson']
    end
    if osm_result['boundingbox'].present?
      boundingbox = osm_result['boundingbox']
    end
    
    data["source"] = source
    data["lat"] = lat
    data["lng"] = lng
    data["formatted_address"] = formatted_address
    data["type"] = type
    if queried_for.present?
      data["queried_for"] = queried_for
    end
    data["boundingbox"] = boundingbox
    if geojson.present?
      data["geojson"] = geojson
    end
    return data
  end
  
  def set_geometry_type
    results = self.results
    if results.blank?
      return
    end

    json = results['geojson']
    if json.present?
      geometry_type = json['type']
      if geometry_type.present?
        self.geometry_type = geometry_type
      end
    end
  end
  
  def decode_geometry
    results = self.results
    if results.blank?
      return nil
    end
    
    json = results['geojson']
    if json.present?
      factory = RGeo::Geographic.spherical_factory(:srid => 4326, :uses_lenient_assertions => true)
      geometry = RGeo::GeoJSON.decode(json, :json_parser => :json, :geo_factory => factory)
      return geometry
    end
    
    return nil
  end
  
  def set_wkb_geometry
    puts "set_wkb_geometry"
    geometry = self.decode_geometry
    if geometry.present?
      self.wkb_geometry = geometry
    end
  end
  
  def set_zip_code
    puts "set_zip_code"
    FindZipCode.perform_async(self.id)
  end
  
  def set_census_tract
    puts "set_census_tract"
    FindCensusTract.perform_async(self.id)
  end
  
  def set_county
    FindCounty.perform_async(self.id)
  end
  
  def set_neighborhood
    FindNeighborhood.perform_async(self.id)
  end
  
  def google_formatted_address
    if self.google_results.present?
      results = self.google_results['results']
      if results.present? && results.length > 0
        formatted_address = results[0]['formatted_address']
        if formatted_address.present?
          return formatted_address
        end
      end
    end
    return nil
  end
  
  def osm_formatted_address
    if self.osm_results.present? && self.osm_results.length > 0
      display_name = self.osm_results[0]['display_name']
      if display_name.present?
        return display_name
      end
    end
    return nil
  end
  
  def set_formatted_address
    results = self.results
    if results.blank?
      return
    end
    
    formatted_address = results['formatted_address']
    if formatted_address.present?
      self.formatted_address = formatted_address
    end    
  end
  
  def set_latlng
    results = self.results
    if results.blank?
      return
    end
    
    lat = results['lat']
    lng = results['lng']
    factory = RGeo::Geographic.spherical_factory(srid: 4326)

    # NOTE: this method takes the LNG parameter first!
    self.latlng = factory.point(lng, lat)
  end
  
  def fetch_osm
    if self.osm_results != nil
      return
    end
    FetchOsm.perform_async(self.id)
  end
  
  def refetch_osm
    FetchOsm.perform_async(self.id)
  end
  
  def fetch_google
    if self.google_results != nil
      return
    end
    FetchGoogle.perform_async(self.id)
  end
  
  def lat
    results = self.results
    if results.present?
      return results["lat"]
    end
    return self.latlng.lat
  end
  
  def lon
    results = self.results
    if results.present?
      return results["lng"]
    end
    return self.latlng.lon
  end
  
  def refetch_google
    FetchGoogle.perform_async(self.id)
  end
  
end

interface/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :show, :edit, :update]

  # GET /locations
  # GET /locations.json
  def index
    if params[:search].present?
      @locations = Location.where("name ILIKE ?", "#{params[:search]}%")
    else
      @locations = Location.all
    end
    
    @locations = @locations.paginate(page: params[:page], per_page: params[:per_page])
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :use_osm, :flagged, :comment, :search, :flag_id)
    end
end

interface/app/helpers/locations_helper.rb
module LocationsHelper
end

interface/app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= location.name %>
  </div>

  <div class="field">
        <%= form.label :comment %>
        <%= form.text_area :comment %>
  </div>
  
  <div class="field">
      <%= form.label :flagged %>
      <%= form.check_box :flagged %>
  </div>
  
  <div class="field">
      <%= form.label :use_osm %>
      <%= form.check_box :use_osm %>
  </div>
  
  <div class="field">
  <%= form.collection_select :flag_id, Flag.order(:reason), :id, :reason, include_blank: "Select Reason" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

interface/app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

interface/app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<p>
<%= form_tag(locations_path, method: :get) do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag 'Search' %>
<% end %>
</p>

<table>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= link_to location.name, location %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @counties %>

<br>

<%= link_to 'New Location', new_location_path %>

interface/app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

interface/app/views/locations/show.html.erb
<% content_for :title, @location.name %>

  <!-- Map Box -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/simple-statistics/1.0.1/simple_statistics.js" integrity="sha256-hC7pS5IxrCj2NpLW8BHhjxcuqAzT9x8NV14WI4Agzlo=" crossorigin="anonymous"></script>
  <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
  <meta name="robots" content="noindex,nofollow">
  <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.6.0/mapbox-gl.js'></script>
  <script src="https://d3js.org/d3.v5.js"></script>
  <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.6.0/mapbox-gl.css' rel='stylesheet' />
  <script src='https://api.mapbox.com/mapbox.js/plugins/turf/v2.0.2/turf.min.js'></script>
  
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>


<p>
  <strong>County:</strong>
  <%= link_to @location.county.try(:name), @location.county %>
</p>

<p>
  <strong>Formatted Address:</strong>
  <%= @location.formatted_address %>
</p>

<p>
  <strong>Bias:</strong>
  <%= @location.bias %>
</p>

<% if @location.results.present? %>

<link href="https://api.mapbox.com/mapbox-gl-js/v1.9.1/mapbox-gl.css" rel="stylesheet">
<div id="map"></div>

<style>
  #map {
      width: 100%;
      height: 400px;
  }
  
</style>

<script>
  mapboxgl.accessToken = '<%= ENV['MAPBOX_ACCESS_TOKEN'] %>';
    var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/streets-v11',
        center: [-98.35, 49.50],
        zoom: 2
    });

    map.on('load', function() {
            
      var locationGeojson = {
      // feature for Mapbox DC
      'type': 'Feature',
      'geometry': <%= raw @location.results['geojson'].to_json %>,
      'properties': {
      'title': "<%= @location.name %>",
      'icon': 'monument'
        }      
      }
      
      var bbox = turf.extent(locationGeojson);
      
      map.addSource('points', {
      'type': 'geojson',
      'data': locationGeojson
      });
            
      <% if @location.geometry_type == "Point" %>
      
      map.addLayer({
      'id': 'points',
      'type': 'symbol',
      'source': 'points',
      'layout': {
      // get the icon name from the source's "icon" property
      // concatenate the name to get an icon from the style's sprite sheet
      'icon-image': ['concat', ['get', 'icon'], '-15'],
      // get the title name from the source's "title" property
      'text-field': ['get', 'title'],
      'text-font': ['Open Sans Semibold', 'Arial Unicode MS Bold'],
      'text-offset': [0, 0.6],
      'text-anchor': 'top'
      }
      });
      
      <% else %>

      map.addLayer({
      'id': 'points',
      'type': 'fill',
      'source': 'points',
      'paint': {
          'fill-color': '#FF0000',
          'fill-opacity': 0.8
      },
      'layout': {}
      });
      
      <% end %>      

        <% if @location.county %>
        var geojson = {
              'type': 'Feature',
              'geometry': <%= raw @location.county.geojson.to_json %>
            }
        bbox = turf.extent(geojson);
        
        map.addSource('county', {
            'type': 'geojson',
            'data': geojson
        });
        map.addLayer({
            'id': 'county',
            'type': 'fill',
            'source': 'county',
            'layout': {},
            'paint': {
                'fill-color': '#088',
                'fill-opacity': 0.5
            }
        });

        <% end %>
        map.fitBounds(bbox, {padding: 20});        
    });
</script>

<% end %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @location.articles.each do |article| %>
      <tr>
        <% if article.collection %>
        <td><%= link_to article.collection.try(:name), article.collection %></td>
        <% else %>
        <td></td>
        <% end %>
        <td><%= link_to article.title, article %></td>
        <td><%= article.authors.pluck(:name) %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <strong>Results:</strong>
  <pre style="background: #00264d;"><%= JSON.pretty_generate(@location.results) %></pre>
</p>

<p>
  <strong>OSM:</strong>
  <pre><%= JSON.pretty_generate(@location.osm_results) %></pre>
</p>

<p>
  <strong>Google:</strong>
  <pre style="background: #054202;"><%= JSON.pretty_generate(@location.google_results) %></pre>
</p>