interface/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :sentences, only: [:show]
  resources :bert_tags, only: [:edit, :update]
  resources :articles
  resources :locations  
  resources :states  
  resources :counties  
  resources :topics  
  resources :neighborhoods  
  resources :zip_codes  
  resources :article_locations  
  resources :collections
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
  
  root to: 'articles#index'
  
  post '/collections(/:id)/import', controller: :collections, action: :import, as: 'import_collections'
  get '/collections(/:id)/points', controller: :collections, action: :points
  get '/collections(/:id)/polys', controller: :collections, action: :polys
  get '/collections(/:id)/map', controller: :collections, action: :map
  get '/collections(/:id)/locations', controller: :collections, action: :locations
  get '/collections(/:id)/locations(/:location_id)', controller: :collections, action: :location
  get '/collections(/:id)/zip_codes', controller: :collections, action: :zip_codes
  get '/collections(/:id)/authors', controller: :collections, action: :authors
  get '/collections(/:id)/topics', controller: :collections, action: :topics
  get '/collections(/:id)/census_tracts', controller: :collections, action: :census_tracts
  get '/collections(/:id)/counties', controller: :collections, action: :counties
  get '/collections(/:id)/neighborhoods', controller: :collections, action: :neighborhoods
  get '/collections(/:id)/featured', controller: :collections, action: :featured
  get '/collections(/:id)/articles', controller: :collections, action: :articles
  get '/collections(/:id)/tasks', controller: :collections, action: :tasks
  get '/collections(/:id)/info', controller: :collections, action: :info
  get '/collections(/:id)/simple_articles', controller: :collections, action: :simple_articles
  get '/collections(/:id)/article_locations', controller: :collections, action: :article_locations
  get '/collections(/:id)/featured_articles', controller: :collections, action: :featured_articles
  get '/collections(/:id)/featured_article_locations', controller: :collections, action: :featured_article_locations
  
end

interface/app/models/collection.rb
class Collection < ApplicationRecord
  
  before_save :will_save
  
  has_many :articles
  has_many :sentences, :through => :articles
  has_many :bert_tags, :through => :sentences
  has_many :locations, :through => :bert_tags
  has_many :article_locations, :through => :articles
  has_many :zip_codes, :through => :locations
    
  validates_numericality_of :max_lat, :greater_than => :min_lat, :allow_nil => true
  validates_numericality_of :max_lng, :greater_than => :min_lng, :allow_nil => true
  
  def filtered_point_ids
    Rails.cache.fetch([self, :filtered_point_ids], expires_in: 2.minutes) { filtered_point_ids! }
  end
  
  def filtered_point_ids!
    if self.bounds.blank?
      return self.point_ids
    end      
    return self.locations.where("geometry_type = ?", "Point").where("ST_Contains(ST_Geomfromtext('#{self.bounds.to_s}', 4326), wkb_geometry)").pluck(:id)
  end
  
  def point_ids(model_version)
    Rails.cache.fetch([self, :point_ids, model_version], expires_in: 2.minutes) { point_ids!(model_version) }
  end
  
  def point_ids!(model_version)
    articles = self.articles
    return Sentence.joins(:bert_tags).where("model_version = ? AND location_id IS NOT NULL AND article_id IN (?)", model_version, articles.pluck(:id).uniq).pluck(:location_id).uniq
  end
  
  def will_save
    if self.lat_changed? || self.lng_changed?
      self.set_center
    end
  end
  
  def max_bounds
    if self.min_lat.blank? || self.min_lng.blank? || self.max_lat.blank? || self.max_lng.blank?
      return nil
    end
    return [[self.min_lng.to_f, self.min_lat.to_f], [self.max_lng.to_f,  self.max_lat.to_f]]
  end
  
  def bounds
    if self.min_lat.blank? || self.min_lng.blank? || self.max_lat.blank? || self.max_lng.blank?
      return nil
    end
    factory = RGeo::Geographic.spherical_factory(:srid => 4326, :uses_lenient_assertions => true)    
    point1 = factory.point(self.min_lng, self.min_lat) 
    point2 = factory.point(self.max_lng, self.max_lat) 
    boundingBox = RGeo::Cartesian::BoundingBox.create_from_points(point1, point2).to_geometry 
    return boundingBox
  end
    
  def viewbox
    if self.min_lat.blank? || self.min_lng.blank? || self.max_lat.blank? || self.max_lng.blank?
      return nil
    end
    return [self.min_lat.to_f, self.min_lng.to_f, self.max_lat.to_f,  self.max_lng.to_f].join(",")
  end
  
  def bias
    "#{self.lat},#{self.lng}"
  end
  
  def set_center
    lat = self.lat
    lng = self.lng
    factory = RGeo::Geographic.spherical_factory(srid: 4326)

    # NOTE: this method takes the LNG parameter first!
    self.center = factory.point(lng, lat)
  end
  
end

interface/app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :map]
  before_action :set_collection, only: [:location, :neighborhoods, :topics, :authors, :info, :show, :edit, :update, :destroy, :article_locations, :articles, :simple_articles, :points, :counties, :locations, :map, :zip_codes, :census_tracts, :polys, :tasks]
  before_action :set_featured, only: [:featured, :featured_articles, :featured_article_locations]
  caches_action :counties, :cache_path => Proc.new { |c| c.request.url }, expires_in: 24.hour
  caches_action :neighborhoods
  caches_action :topics
  caches_action :authors
  caches_action :zip_codes
  caches_action :census_tracts
  caches_action :points, :if => Proc.new { |c| @collection.cached }, :cache_path => Proc.new { |c| c.request.url }
  
  def import
    Article.import_file(params[:id], params[:file])
    redirect_to root_url, notice: "Articles imported."
  end
  
  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
  end
  
  # GET /collections/1/map
  def map
    redirect_to "https://coverage-analysis.herokuapp.com/collections/#{@collection.id}"
  end
  
  # GET /collections/1/locations
  def locations
    @locations = @collection.locations
  end
  
  # GET /collections/1/locations/1
  def location
    response.headers.delete "X-Frame-Options"
    
    location_id = params[:location_id]
    @location = @collection.locations.where("locations.id = ?", location_id).first

    article_ids = @collection.article_ids
    article_ids = ArticleLocation.where("article_id IN (?) AND location_id = ?", article_ids, location_id).pluck(:article_id)
    @articles = Article.where("id IN (?)", article_ids)
  end
  
  # GET /collections/1/counties
  def counties
    if params[:county_ids]
      ids = params[:county_ids].split(',').map(&:to_i)
    else
      @locations = @collection.locations
      ids = @locations.pluck(:county_id)
    end
    @counties = County.where("ogc_fid IN (?)", ids).where("geoid IS NOT NULL")
  end
  
  # GET /collections/1/neighborhoods
  def neighborhoods
    @locations = @collection.locations
    ids = @locations.pluck(:neighborhood_id)
    @neighborhoods = Neighborhood.where("ogc_fid IN (?)", ids).where("geoid_nh IS NOT NULL")
  end
  
  # GET /collections/1/featured
  def featured
    respond_to do |format|
      format.html { redirect_to controller: 'collections', action: 'counties', id: params[:id], county_ids: @featured_county_ids, before: @featured_before, after: @featured_after, format: "html", per_page: 4 }
      format.json { redirect_to controller: 'collections', action: 'counties', id: params[:id], county_ids: @featured_county_ids, before: @featured_before, after: @featured_after, format: "json" }
    end
  end
  
  # GET /collections/1/featured_articles
  def featured_articles
    respond_to do |format|
      format.html { redirect_to controller: 'collections', action: 'articles', id: params[:id], county_ids: @featured_county_ids, before: @featured_before, after: @featured_after, format: "html", per_page: 4 }
      format.json { redirect_to controller: 'collections', action: 'articles', id: params[:id], county_ids: @featured_county_ids, before: @featured_before, after: @featured_after, format: "json" }
    end
  end
    
  def featured_article_locations
    respond_to do |format|
      format.html { redirect_to controller: 'collections', action: 'article_locations', id: params[:id], county_ids: @featured_county_ids, before: params[:before], after: params[:after], format: "html", per_page: 4 }
      format.json { redirect_to controller: 'collections', action: 'article_locations', id: params[:id], county_ids: @featured_county_ids, before: params[:before], after: params[:after], format: "json" }
    end
  end
  
  # GET /collections/1/zip_codes
  def zip_codes
    ids = @collection.locations.where("zip_code_id IS NOT NULL").pluck(:zip_code_id)
    @zip_codes = ZipCode.where("ogc_fid IN (?)", ids).pluck(:zcta5ce10)
    render json: @zip_codes.uniq
  end
  
  # GET /collections/1/authors
  def authors
    author_ids = ArticleAuthor.where("article_id IN (?)", @collection.article_ids).pluck(:author_id)
    @authors = Author.where("id IN (?)", author_ids)
  end
  
  # GET /collections/1/topics
  def topics
    topic_ids = ArticleTopic.where("article_id IN (?)", @collection.article_ids).pluck(:topic_id)
    @topics = Topic.where("id IN (?)", topic_ids)
  end
  
  # GET /collections/1/census_tracts
  def census_tracts
    ids = @collection.locations.where("census_tract_id IS NOT NULL").pluck(:census_tract_id)
    @census_tracts = CensusTract.where("ogc_fid IN (?)", ids).where("geoid IS NOT NULL")
  end

  # GET /collections/1/points.json
  def points    
    model_version = params.fetch(:model_version, "v1")
    if params[:before] or params[:after]
      articles = @collection.articles
      if params[:before]
       articles = articles.before(params[:before])
      end
      if params[:after]
       articles = articles.after(params[:after])
      end
      point_ids = Sentence.joins(:bert_tags).where("model_version = ? AND location_id IS NOT NULL AND article_id IN (?)", model_version, articles.pluck(:id).uniq).pluck(:location_id).uniq
    else
      point_ids = @collection.point_ids(model_version)
    end
    
    @locations = Location.where("id IN (?)", point_ids).where("geometry_type = ?", "Point")

    if params[:bind].present? and @collection.bounds.present?
      @locations = @locations.where("ST_Contains(ST_Geomfromtext('#{@collection.bounds.to_s}', 4326), wkb_geometry)")
    end
        
    if params[:zipcode].present?
      zipcode = ZipCode.find_by_zcta5ce10(params[:zipcode])
      @locations = @locations.where("zip_code_id = ?", zipcode.ogc_fid)
    end        
  
    if params[:neighborhood_id].present?
      @locations = @locations.where("neighborhood_id =?", params[:neighborhood_id])
    end
        
    @locations = @locations.paginate(page: params[:page], per_page: params[:per_page])
      
    respond_to do |format|
       format.xlsx
       format.json { render json: PointBlueprint.render(@locations) }
     end
  end
  
  # GET /collections/1/polys.json
  def polys
    @locations = @collection.locations.where("geometry_type != ?", "Point").uniq
    features = @locations.map { |val| val.feature }
    
    render json: {
        "type": "FeatureCollection",
        "name": "clip-points-co-ct-nh",
        "crs": {
            "type": "name",
            "properties": {
                "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
            }
        },
        "features": features
      }
    
  end
  
  # GET /collections/1/article_locations
  # GET /collections/1/article_locations.json
  def article_locations
    article_locations = @collection.article_locations
    if params[:before]
     article_locations = article_locations.joins(:location).before(params[:before])
    end
    if params[:after]
     article_locations = article_locations.joins(:location).after(params[:after])
    end
    if params[:county_ids]
      ids = params[:county_ids].split(',').map(&:to_i)
      article_locations = article_locations.where("county_id IN (?)", ids)
    end
    if params[:flagged].present?
      flagged = ActiveRecord::Type::Boolean.new.deserialize(params[:flagged])
      if flagged
        article_locations = article_locations.where("article_locations.flagged = true OR locations.flagged = true")
      else
        article_locations = article_locations.where("article_locations.flagged = false AND locations.flagged = false")
      end
    end
    
    @article_locations = article_locations.includes(:article, :location).order("locations.county_id, locations.id")
  end
  
  # GET /collections/1/articles
  # GET /collections/1/articles.json
  def articles
    articles = @collection.articles
    if params[:before]
     articles = articles.before(params[:before])
    end
    if params[:after]
     articles = articles.after(params[:after])
    end
    if params[:county_ids]
      ids = params[:county_ids].split(',').map(&:to_i)
      articles = articles.where("locations.county_id IN (?)", ids)
    end
    articles = articles.includes(:article_locations => :location)
    articles = articles.joins(:article_locations => :location)
    if params[:flagged].present?
      flagged = ActiveRecord::Type::Boolean.new.deserialize(params[:flagged])
      if flagged
        articles = articles.where("article_locations.flagged = true OR locations.flagged = true")
      else
        articles = articles.where("article_locations.flagged = false AND locations.flagged = false")
      end
    end  
    @articles = articles.order("published_at DESC")
  end
  
  # GET /collections/1/simple_articles
  # GET /collections/1/simple_articles.json
  def simple_articles
    articles = @collection.articles
    
    if params[:zipcode].present?
      articles = articles.joins(:article_locations => :location)
      zipcode = ZipCode.find_by_zcta5ce10(params[:zipcode])
      articles = articles.where("locations.zip_code_id = ?", zipcode.ogc_fid)
    end
    if params[:before]
     articles = articles.before(params[:before])
    end
    if params[:after]
     articles = articles.after(params[:after])
    end
    if params[:county_ids]
      ids = params[:county_ids].split(',').map(&:to_i)
      articles = articles.where("locations.county_id IN (?)", ids)
    end
    if params[:flagged].present?
      articles = articles.includes(:article_locations => :location)
      articles = articles.joins(:article_locations => :location)
      flagged = ActiveRecord::Type::Boolean.new.deserialize(params[:flagged])
      if flagged
        articles = articles.where("article_locations.flagged = true OR locations.flagged = true")
      else
        articles = articles.where("article_locations.flagged = false AND locations.flagged = false")
      end
    end  
        
    count = articles.count
    

interface/app/helpers/collections_helper.rb
module CollectionsHelper
end

interface/app/views/collections/_form.html.erb
<%= form_with(model: collection, local: true) do |form| %>
  <% if collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <div class="field">
    <%= form.label :lat %>
    <%= form.number_field :lat, step: :any %>
  </div>
    
  <div class="field">
    <%= form.label :lng %>
    <%= form.number_field :lng, step: :any %>
  </div>
  
  <div class="field">
    <%= form.label :km_radius %>
    <%= form.number_field :km_radius, step: 0.001 %>
  </div>
  
  <div class="field">
    <%= form.label :min_lat %>
    <%= form.number_field :min_lat, step: 0.001 %>
  </div>
    
  <div class="field">
    <%= form.label :min_lng %>
    <%= form.number_field :min_lng, step: 0.001 %>
  </div>
  
  <div class="field">
    <%= form.label :max_lat %>
    <%= form.number_field :max_lat, step: 0.001 %>
  </div>
    
  <div class="field">
    <%= form.label :max_lng %>
    <%= form.number_field :max_lng, step: 0.001 %>
  </div>
  
  <div class="field">
  <a href="http://bboxfinder.com/#<%=collection.viewbox %>" target="_blank">Bounding Box Tool</a>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

interface/app/views/collections/article_locations.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @collection.name %>
</p>

<table>
  <thead>
    <tr>
      <th>County</th>
      <th>Location</th>
      <th>Title</th>
      <th>Published</th>
      <th>Flagged</th>
      <th colspan="2"></th>
    </tr>
  </thead>
 
  <tbody>
    <% @article_locations.each do |article_location| %>
      <tr>
        <td><%= article_location.location.county.try(:name) %></td>
        <td><%= article_location.location.try(:name) %></td>
        <td><%= link_to article_location.article.title, article_location.article.source_url %></td>
        <td><%= article_location.article.published_at %></td>
        <td><%= article_location.flagged %></td>
        <td><%= link_to 'Edit', edit_article_location_path(article_location) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  Download:
  <%= link_to "CSV", collection_path(@collection, format: "csv") %>
</p>

<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %> |
<%= link_to 'Map', collection_path(@collection) + '/map' %> |
<%= link_to 'Locations', collection_path(@collection) + '/locations' %>

interface/app/views/collections/articles.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @collection.name %>
</p>

<table>
  <thead>
    <tr>
      <th>Published</th>
      <th>Author</th>
      <th>Title</th>
      <th>Locations Count</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.published_at %></td>
        <td><%= article.authors.pluck(:name) %></td>
        <td><%= link_to article.title, article %></td>
        <td><%= article.article_locations_count %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  Download:
  <%= link_to "CSV", collection_path(@collection, format: "csv") %>
</p>

<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %> |
<%= link_to 'Map', collection_path(@collection) + '/map' %> |
<%= link_to 'Locations', collection_path(@collection) + '/locations' %>

interface/app/views/collections/counties.html.erb
<p id="notice"><%= notice %></p>

<h1>Counties</h1>

<table>

  <tbody>
    <% @counties.each do |county| %>
      <tr>
        <td><h3><%= link_to "#{county.description}", county %></h3>
            <% county.locations.each do |location| %>
                <% article_locations = ArticleLocation.joins(:article).where("location_id = ? AND collection_id = ?", location.id, @collection.id) %>
                <% if params[:before] %>
                <%  article_locations = article_locations.before(params[:before]) %>
                <% end %>
                <% if params[:after] %>
                <%  article_locations = article_locations.after(params[:after]) %>
                <% end %>
                <% count = article_locations.count %>
                <% if count > 0 %>
                  <p><%= link_to location.name, location %> -> <%= location.formatted_address %></p>
                  <% article_locations.each do |article_location| %>
                      <div style="margin-left: 40px; font-size: 12px">
                        <div style="toppadding: 10px; font-size: 14px">
                          <% if article_location.article.published_at %>
                          <b><%= article_location.article.published_at.strftime('%a %b %e, %H:%M:%S %Z %Y') %></b> -
                          <% end %>
                          <% if article_location.article.source_url %>
                          <%= link_to article_location.article.title, article_location.article.source_url, target: :_blank  %>
                          <% else %>
                          <%= article_location.article.title %>
                          <% end %>
                        </div>
                        <div style="padding-top: 3px; padding-bottom: 5px;">
                        <span style="color: gray; padding: 10px;"><%= article_location.snippet.html_safe %></span>                      
                        </div>
                        <div style="toppadding: 10px;">
                          <span style="background-color: #FFFFCC; margin-right:5px;">
                          <%= link_to "View Data", article_location.article, style: "text-decoration: none; font-size: 12px" %>
                          </span>
                          <span style="background-color: #FFBAD2; margin-right:5px;">
                          <%= link_to 'Destroy Location Reference', article_location, method: :delete, data: { confirm: 'Are you delete the connection between the article and this location?' }, style: "text-decoration: none;" %>
                          </span>
                        </div>
                      </div>
                  <% end %>
                <% end %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @counties %>

interface/app/views/collections/edit.html.erb
<h1>Editing Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

interface/app/views/collections/featured.html.erb
<p id="notice"><%= notice %></p>

<h1>Featured</h1>
<% article_ids = @collection.articles.pluck(:id) %>
<table>

  <tbody>
    <% @counties.each do |county| %>
      <tr>
        <td><%= link_to county.description, county %>
            <% county.locations.each do |location| %>
                <% ids = article_ids & ArticleLocation.where("location_id = ?", location.id).pluck(:article_id) %>
                <% if ids.count > 0 %>
                  <p style="margin-left: 40px;"><%= link_to location.name, location %> -> <%= location.formatted_address %> (<%= ids.count %>)</p>
                  <% Article.where("id IN (?)", ids).each do |article| %>
                      <p style="margin-left: 80px;"><%= link_to article.title, article %></p>
                  <% end %>
                <% end %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

interface/app/views/collections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Collections</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.name %></td>
        <td><%= link_to 'Show', collection %></td>
        <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
        <td><%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collection', new_collection_path %>

interface/app/views/collections/locations.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= link_to location.name, location %>
            <% location.articles.where("collection_id = ?", @collection.id).each do |article| %>
                <p style="margin-left: 40px;"><%= link_to article.title, article %></p>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

interface/app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Back', collections_path %>

interface/app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @collection.name %>
</p>

<table>
  <thead>
    <tr>
      <th>Published</th>
      <th>Author</th>
      <th>Title</th>
      <th>Locations Count</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.published_at %></td>
        <td><%= article.authors.pluck(:name) %></td>
        <td><%= link_to article.title, article %></td>
        <td><%= article.article_locations_count %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @articles %>

<h2>Import Articles</h2>

<%= form_tag import_collections_path(@collection), multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<br>

<p>
  Download:
  <%= link_to "CSV", collection_path(@collection, format: "csv") %>
</p>

<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %> |
<%= link_to 'Map', collection_path(@collection) + '/map' %> |
<%= link_to 'Locations', collection_path(@collection) + '/locations' %>

interface/app/views/collections/simple_articles.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @collection.name %>
</p>

<table>
  <thead>
    <tr>
      <th>Published</th>
      <th>Author</th>
      <th>Title</th>
      <th>Locations Count</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.published_at %></td>
        <td><%= article.authors.pluck(:name) %></td>
        <td><%= link_to article.title, article %></td>
        <td><%= article.article_locations_count %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  Download:
  <%= link_to "CSV", collection_path(@collection, format: "csv") %>
</p>

<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %> |
<%= link_to 'Map', collection_path(@collection) + '/map' %> |
<%= link_to 'Locations', collection_path(@collection) + '/locations' %>

interface/app/views/collections/tasks.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @collection.name %>
</p>

<table>
  <thead>
    <tr>
      <th>Published</th>
      <th>Author</th>
      <th>Title</th>
      <th>Locations Count</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.published_at %></td>
        <td><%= article.authors.pluck(:name) %></td>
        <td><%= link_to article.title, article %></td>
        <td><%= article.article_locations_count %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  Download:
  <%= link_to "CSV", collection_path(@collection, format: "csv") %>
</p>

<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %> |
<%= link_to 'Map', collection_path(@collection) + '/map' %> |
<%= link_to 'Locations', collection_path(@collection) + '/locations' %>

interface/app/views/collections/zip_codes.html.erb
<p id="notice"><%= notice %></p>

<h1>Zip Codes</h1>

<table>

  <tbody>
    <% @zip_codes.each do |zip_code| %>
      <tr>
        <td><%= link_to zip_code.zcta5ce10, zip_code %>
            <% zip_code.locations.each do |location| %>
                <p style="margin-left: 40px;"><%= link_to location.name, location %></p>
                <% location.articles.where("articles.id IN (?)", @collection.articles.pluck(:id)).each do |article| %>
                    <p style="margin-left: 80px;"><%= link_to article.title, article %></p>
                <% end %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>